import type { Product } from "@/types/product";

export const MOCK_PRODUCTS: Product[] = [
  {
    id: "macbook-pro-14",
    name: 'MacBook Pro 14"',
    sku: "MBP14M3PRO",
    description: "",
    manufacturer: "Apple",
    category: "computers",
    features: ["wifi", "bluetooth", "usbC", "premium"],
    netPriceCents: 812927,
    grossPriceCents: 999900,
    vatRate: 23,
    currency: "PLN",
    isAvailable: true,
    isLimited: false,
    stockQuantity: null,
    minQuantity: 1,
    maxQuantity: 10,
  },
  {
    id: "galaxy-s24-ultra",
    name: "Galaxy S24 Ultra",
    sku: "SGS24U256",
    description: "",
    manufacturer: "Samsung",
    category: "phones",
    features: ["wifi", "bluetooth", "usbC", "waterproof"],
    netPriceCents: 512114,
    grossPriceCents: 629900,
    vatRate: 23,
    currency: "PLN",
    isAvailable: true,
    isLimited: true,
    stockQuantity: 45,
    minQuantity: 1,
    maxQuantity: 10,
  },
  {
    id: "sony-wh-1000xm5",
    name: "Sony WH-1000XM5",
    sku: "SNWH1000XM5",
    description: "",
    manufacturer: "Sony",
    category: "tv",
    features: ["bluetooth", "wireless", "premium"],
    netPriceCents: 130000,
    grossPriceCents: 159900,
    vatRate: 23,
    currency: "PLN",
    isAvailable: true,
    isLimited: false,
    stockQuantity: null,
    minQuantity: 1,
    maxQuantity: 10,
  },
  {
    id: "bosch-serie-6",
    name: "Bosch Serie 6 WAU28P40",
    sku: "BSWAU28P40",
    description: "",
    manufacturer: "Bosch",
    category: "appliances",
    features: ["ecoFriendly"],
    netPriceCents: 268211,
    grossPriceCents: 329900,
    vatRate: 23,
    currency: "PLN",
    isAvailable: false,
    isLimited: true,
    stockQuantity: 0,
    minQuantity: 1,
    maxQuantity: 10,
  },
  {
    id: "xiaomi-smart-band-8",
    name: "Xiaomi Smart Band 8",
    sku: "XMSB8BLK",
    description: "",
    manufacturer: "Xiaomi",
    category: "accessories",
    features: ["bluetooth", "waterproof"],
    netPriceCents: 14553,
    grossPriceCents: 17900,
    vatRate: 23,
    currency: "PLN",
    isAvailable: true,
    isLimited: false,
    stockQuantity: null,
    minQuantity: 1,
    maxQuantity: 10,
  },
];
